export const ADD_TODO = 'todos/addTodo'
export const TOGGLE_TODO = 'todos/toggleTodo'
export const UPDATE_TODO = 'todos/updateTodo'
export const DELETE_TODO = 'todos/deleteTodo'
export const TOGGLE_FORM = 'todos/toggleForm'
export const GET_TODOS = 'todos/getTodos'
export const SHOW_LOADER = 'todos/showLoader'
export const HIDE_LOADER = 'todos/hideLoader'